### ISSUE TITLE
Issue with tsconfig.json stray comma prevents start up

### ISSUE THREAD

**Issue by Saltallica** [yoDon/electron-dotnet#7]
Thanks for sharing this cool project!

In your tsconfig.json, there is a stray comma on line 22

```
"noEmit": true,
```

This causes all sorts of badness:

```
SyntaxError: C:\Projects\sws-log-viewer\tsconfig.json: Unexpected token } in JSON at position 575
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:763:27)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at getModules (C:\Projects\sws-log-viewer\node_modules\react-scripts\config\modules.js:74:14)
    at Object.<anonymous> (C:\Projects\sws-log-viewer\node_modules\react-scripts\config\modules.js:92:18)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

Removing the stray comma allows for building.

**Comment by yoDon** [comment]
Thanks - I suspect it was a difference in editor settings of whether the tsconfig should be parsed as json or json-with-comments, but regardless it should be fixed now
